handle infrequent NPE from Swing
stack trace:
java.lang.NullPointerException: Cannot invoke "javax.swing.text.View.getMinimumSpan(int)" because "v" is null
	at java.desktop/javax.swing.text.BoxView.calculateMajorAxisRequirements(BoxView.java:872)
	at java.desktop/javax.swing.text.BoxView.checkRequests(BoxView.java:931)
	at java.desktop/javax.swing.text.BoxView.getMinimumSpan(BoxView.java:569)
	at java.desktop/javax.swing.text.BoxView.calculateMajorAxisRequirements(BoxView.java:872)
	at java.desktop/javax.swing.text.BoxView.checkRequests(BoxView.java:931)
	at java.desktop/javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:330)
	at java.desktop/javax.swing.text.BoxView.layout(BoxView.java:710)
	at java.desktop/javax.swing.text.BoxView.setSize(BoxView.java:398)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI$RootView.setSize(BasicTextUI.java:1823)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI.modelToView(BasicTextUI.java:1104)
	at java.desktop/javax.swing.plaf.basic.BasicTextUI.modelToView2D(BasicTextUI.java:1090)
	at java.desktop/javax.swing.text.JTextComponent.modelToView2D(JTextComponent.java:1410)
	at org.zephyrsoft.sdb2.presenter.SongView.moveToLine(SongView.java:484)
	at org.zephyrsoft.sdb2.presenter.PresenterWindow.setContent(PresenterWindow.java:173)
	at org.zephyrsoft.sdb2.presenter.PresenterBundle.setContent(PresenterBundle.java:50)
	at org.zephyrsoft.sdb2.MainController.present(MainController.java:261)
	at org.zephyrsoft.sdb2.gui.MainWindow.presentSong(MainWindow.java:1475)
	at org.zephyrsoft.sdb2.gui.MainWindow.handleSongPresent(MainWindow.java:1466)